esphome:
  name: testboard

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  js_include: "./v2/www.js"
  js_url: ""
  version: 2

wifi:
  ap: {}
  # ssid: "TP-LINK_EAF7FC"
  # password: !secret wifi_password

# HC4067 Multiplexor
switch:
  - platform: gpio
    pin: 16
    name: "S3"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 4
    name: "S2"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: 2
    name: "S1"
    restore_mode: ALWAYS_ON

  - platform: gpio
    pin: 15
    name: "S0"
    restore_mode: ALWAYS_OFF
