esphome:
  name: testboard

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  js_include: "./v2/www.js"
  js_url: ""
  version: 2

wifi:
  ssid: "TP-LINK_EAF7FC"
  password: !secret wifi_password
