esphome:
  name: testboard

esp32:
  board: esp32doit-devkit-v1
  framework:
    type: arduino

# Enable logging
logger:

web_server:
  js_include: "./v2/www.js"
  js_url: ""
  version: 2

wifi:
  ap: {}
  # ssid: "TP-LINK_EAF7FC"
  # password: !secret wifi_password

# Example configuration entry for ESP32
i2c:
  sda: GPIO21
  scl: GPIO22
  scan: true
  id: bus_a

# I2C output expansor
pcf8574:
  - id: "pcf8574_hub"
    address: 0x21
    pcf8575: false

# Individual outputs
switch:
  # PCF8574 outputs
  - platform: gpio
    name: "Data out1"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      # Use pin number 0
      number: 0
      # One of INPUT or OUTPUT
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out2"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 1
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out3"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 2
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out4"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 3
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out5"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 4
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out6"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 5
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out7"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 6
      mode:
        output: true
      inverted: false

  - platform: gpio
    name: "Data out8"
    restore_mode: ALWAYS_OFF
    pin:
      pcf8574: pcf8574_hub
      number: 7
      mode:
        output: true
      inverted: false

  # HC4067 Multiplexor
  - platform: gpio
    pin: GPIO16
    name: "S3"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO04
    name: "S2"
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO02
    name: "S1"
    restore_mode: ALWAYS_ON

  - platform: gpio
    pin: GPIO15
    name: "S0"
    restore_mode: ALWAYS_OFF

  # Enable 74HC373D
  - platform: gpio
    pin: GPIO27
    name: "OE U07"
    id: oe_u7
    interlock: [oe_u8]
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO14
    name: "OE U08"
    id: oe_u8
    interlock: [oe_u7]
    restore_mode: ALWAYS_OFF

  # Enable 74HC242D
  - platform: gpio
    pin: GPIO12
    name: "OE U09"
    id: oe_u9
    interlock: [oe_u10]
    restore_mode: ALWAYS_OFF

  - platform: gpio
    pin: GPIO13
    name: "OE U10"
    id: oe_u10
    interlock: [oe_u9]
    restore_mode: ALWAYS_OFF

spi:
  clk_pin: GPIO18
  miso_pin: GPIO19

# SPI ADC (not the same model!)
mcp3204:
  cs_pin: GPIO05
  reference_voltage: 3.3V

# Example config of sensors.
sensor:
  - platform: mcp3204 # Attached to pin 0 of the MCP3204.
    update_interval: 1s
    id: analog_value
    number: 0 # MCP3204 pin number

# Example configuration entry
binary_sensor:
  - platform: gpio
    pin: GPIO36
    name: "Data In 8"

  - platform: gpio
    pin: GPIO39
    name: "Data In 7"

  - platform: gpio
    pin: GPIO34
    name: "Data In 6"

  - platform: gpio
    pin: GPIO35
    name: "Data In 5"

  - platform: gpio
    pin: GPIO32
    name: "Data In 4"

  - platform: gpio
    pin: GPIO33
    name: "Data In 3"

  - platform: gpio
    pin: GPIO25
    name: "Data In 2"

  - platform: gpio
    pin: GPIO26
    name: "Data In 1"
